#!/usr/bin/env python

import sys
import os
import random
import string 
import termios
import fcntl
import struct
import time

SYSCHECK_INTERVAL=100

def syscheck():
    width, height = 80, 24
    ctx = dict(width=width, height=height)
    return ctx

def main():
    iter = 0
    ctx = syscheck()
    print "\033[32m\033[40m",
    sys.stdout.write('\r')
    sys.stdout.flush()
    for line in sys.stdin:
       iter += 1
       if not iter % SYSCHECK_INTERVAL:
          ctx = syscheck()

       out = ''.join(random.choice('~!#$%^&*(){}`0[]/=\?|-_***********' + (' ' * 50)) for x in range(ctx['width']))
       print out
              

if __name__=='__main__':
   rst = os.popen('tput sgr0').read()
   try:
      main()
   except KeyboardInterrupt:
      pass
   finally:
      print rst,
